version: '3.3'

services:
  python2:
    build:
      context: ./containers/python
      args:
        - PY_VERSION=2.7
    volumes:
      - "~/Projects:/home/docker/Projects"
    entrypoint: "/home/docker/run.sh"

  python3:
    build:
      context: ./containers/python
      args:
        - PY_VERSION=3
    volumes:
      - "~/Projects:/home/docker/Projects"
    entrypoint: "/home/docker/run.sh"

  php:
    build:
      context: ./containers/php
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    volumes:
      - "~/Projects:/home/docker/Projects"
    networks:
      - default
    entrypoint: "/home/docker/run.sh"

  javascript:
    build:
      context: ./containers/javascript
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "~/Projects:/home/docker/Projects"
    entrypoint: "/home/docker/run.sh"

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_PORT=3306
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    networks:
      default:
        aliases:
          - mysql.dockerlink

  oracle:
    build:
      context: ./containers/oracle
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
        - "127.0.0.1:8080:8080"
        - "127.0.0.1:1521:1521"
    entrypoint: "/root/run.sh"

networks:
  default:
